// Code generated by cmd/cgo; DO NOT EDIT.

//line test.go:1:1

package main

// #cgo LDFLAGS: -L. -lfoo
// #cgo CFLAGS: -I.
// #include <stdio.h>
// int foo_say_hi();
// typedef int (*intFunc) ();
//
// int
// bridge_int_func(intFunc f)
// {
//		return f();
// }
//
// int fortytwo()
// {
//	    return 42;
// }
import _ "unsafe"
import "fmt"

func main() {
	( /*line :24:2*/_Cfunc_foo_say_hi /*line :24:13*/)()
	f :=  /*line :25:7*/_Ctype_intFunc /*line :25:16*/(( /*line :25:17*/_Cgo_ptr(_Cfpvar_fp_fortytwo) /*line :25:26*/))
	fmt.Println(int(( /*line :26:18*/_Cfunc_bridge_int_func /*line :26:34*/)(f)))
	// Output: 42
}